services:
  mysql:
    image: mysql:8
    container_name: project_tracker_mysql
    environment:
      MYSQL_DATABASE: project_tracker_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  mongo:
    image: mongo:6
    container_name: project_tracker_mongo
    environment:
      MONGO_INIT_DB_DATABASE: audit_logs
    ports:
      - "27017:27017"

  backend:
    build:
      context:  .
      dockerfile: Dockerfile
    container_name: project_tracker_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongo
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: project_tracker_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root

      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: audit_logs
